-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title VARCHAR(30),
  url VARCHAR(30),
  rating numeric,
  description text
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating, description)
values
  ('Facebook', 'http://www.facebook.com', 3, 'connect with friends'),
  ('Google', 'http://www.google.com', 4, 'search stuff'),
  ('Fun', 'http://www.fun.com', 1, 'lots of fun'),
  ('Thinkful', 'http://www.thinkful.com', 2, 'coding bootcamp'),
  ('Recipes', 'http://www.recipes.com', 3, 'search recipes'),
  ('Amazon', 'http://www.amazon.com', 5, 'search and buy stuff'),
  ('ESPN', 'http://www.espn.com', 4, 'sports news'),
  ('ABC', 'http://www.abc.com', 3, 'watch tv shows'),
  ('Netflix', 'http://www.netflix.com', 5, 'watch favorite tv and movies'),
  ('Weather', 'http://www.weather.com', 1, 'get the weather in your area');
 